version 0.2.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,3 @@
-#!/usr/bin/env bash
 # Anticonf script by Jeroen Ooms (2020)
 # The script will try 'pkg-config' to find required cflags and ldflags.
 # Make sure this executable is in PATH when installing the package.
@@ -14,20 +13,22 @@ PKG_BREW_NAME="cairo"
 PKG_LIBS="-lcairo -lfreetype"
 PKG_TEST_FILE="src/tests/sysdeps.c"
 
-# Use pkg-config if available
-if [ $(command -v pkg-config) ]; then
-  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH:"
-  PKGCONFIG_CFLAGS=$(pkg-config --cflags ${PKG_CONFIG_NAME})
-  PKGCONFIG_LIBS=$(pkg-config --libs ${PKG_CONFIG_NAME})
-
-  # Workaround because cairo.pc on solaris 10 fails to find ft headers
-  if [ $(uname) = "SunOS" ]; then
-    PKGCONFIG_CFLAGS=$(pkg-config --cflags cairo freetype2)
+# Prefer static linking on MacOS
+if [ `uname` = "Darwin" ]; then
+PKG_CONFIG_NAME="--static $PKG_CONFIG_NAME"
+  if [ `arch` = "i386" ]; then
+    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
   fi
 fi
 
-# Hack: we really want our own cairo, not the CRAN one (which depends on XQuartz)
-if [ -e "/Builds/CRAN-QA-Simon" ] || [ -e "/Volumes/Builds" ]; then
+# Use pkg-config if available
+if [ `command -v pkg-config` ]; then
+  PKGCONFIG_CFLAGS=`pkg-config --cflags ${PKG_CONFIG_NAME}`
+  PKGCONFIG_LIBS=`pkg-config --libs ${PKG_CONFIG_NAME}`
+fi
+
+# On CRAN do not use pkgconfig cairo (which depends on XQuartz)
+if [ -d "/Builds/CRAN-QA-Simon" ] || [ -d "/Volumes/Builds" ]; then
   unset PKGCONFIG_CFLAGS
   unset PKGCONFIG_LIBS
 fi
@@ -41,21 +42,22 @@ elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
   echo "Found pkg-config cflags and libs!"
   PKG_CFLAGS=${PKGCONFIG_CFLAGS}
   PKG_LIBS=${PKGCONFIG_LIBS}
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-  if [ $(command -v brew) ]; then
-    BREWDIR=$(brew --prefix)
-    PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include/cairo -I/usr/local/opt/freetype/include/freetype2"
-    PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
+elif [ `uname` = "Darwin" ]; then
+  brew --version 2>/dev/null
+  if [ $? -eq 0 ]; then
+    BREWDIR=`brew --prefix`
+    PKG_CFLAGS="-I$BREWDIR/include/cairo -I$BREWDIR/include/fontconfig -I$BREWDIR/include/freetype2"
+    PKG_LIBS="-L$BREWDIR/lib $PKG_LIBS"
   else
-    curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
-    source autobrew
+    curl -sfL "https://autobrew.github.io/scripts/cairo" > autobrew
+    . autobrew
   fi
 fi
 
 # Find compiler
-CC=$(${R_HOME}/bin/R CMD config CC)
-CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
-CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
+CC=`${R_HOME}/bin/R CMD config CC`
+CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
+CPPFLAGS=`${R_HOME}/bin/R CMD config CPPFLAGS`
 
 # For debugging
 echo "Using PKG_CFLAGS=$PKG_CFLAGS"
@@ -65,12 +67,12 @@ echo "Using PKG_LIBS=$PKG_LIBS"
 ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E ${PKG_TEST_FILE} >/dev/null 2>configure.log
 if [ $? -ne 0 ]; then
   echo "-----------------------------[ ANTICONF ]-------------------------------"
-  echo "Configuration failed to find Cairo or Freetype2. Try installing:"
+  echo "Configuration failed to find libraries. Try installing:"
   echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu)"
   echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
   echo " * csw: $PKG_CSW_NAME (Solaris)"
   echo " * brew: $PKG_BREW_NAME (OSX)"
-  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+  echo "If $PKG_CONFIG_NAME are already installed, check that 'pkg-config' is in your"
   echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
   echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
